# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: focuzo 0.1.0 ruby lib

Gem::Specification.new do |s|
  s.name = "focuzo"
  s.version = "0.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib"]
  s.authors = ["Victor Antoniazzi"]
  s.date = "2015-05-16"
  s.description = "Awesome project"
  s.email = "vgsantoniazzi@gmail.com"
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.rdoc"
  ]
  s.files = [
    ".document",
    ".rspec",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "focuzo.gemspec",
    "lib/api.rb",
    "lib/focuzo.rb",
    "spec/spec_helper.rb",
    "spec/test_spec.rb"
  ]
  s.homepage = "http://github.com/vgsantoniazzi@gmail.com/focuzo"
  s.licenses = ["MIT"]
  s.rubygems_version = "2.4.7"
  s.summary = "Light semaphore lamp through Arduino"

  if s.respond_to? :specification_version then
    s.specification_version = 4

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<rspec>, [">= 0"])
      s.add_runtime_dependency(%q<jeweler>, [">= 0"])
    else
      s.add_dependency(%q<rspec>, [">= 0"])
      s.add_dependency(%q<jeweler>, [">= 0"])
    end
  else
    s.add_dependency(%q<rspec>, [">= 0"])
    s.add_dependency(%q<jeweler>, [">= 0"])
  end
end

